.TH ISCSIADM 8 "July 2005" "" "Linux Administrator's Manual"
.SH NAME
iscsiadm \- open-iscsi administration utility
.SH SYNOPSIS
\fBiscsiadm\fR -m discovery [ -dhV ] [ -t type -p ip [ -l ] ] | [ -r recid ]
[ -o operation ] [ -n name ] [ -v value ]

\fBiscsiadm\fR -m node [ -dhV ] [ -S ] [ [ -r recid | -M sysdir ] [ -l | -u ] ]
[ [ -o operation ]  [ -n name ] [ -v value ] [ -p ip ] ]

\fBiscsiadm\fR -m session [ -dhV ] [ -r [sid:]recid [ -u | -s ] ]

.SH "DESCRIPTION"
The iscsiadm utility is a command-line tool allowing discovery and login
to iSCSI targets, as well as access and management of the open-iscsi
database.
.PP
Note that many of the node and discovery operations require that the iSCSI
daemon (iscsid) be running.

.SH OPTIONS

.TP
\fB\-d\fR, \fB\-\-debug\fR
print debugging information

.TP
\fB\-h\fR, \fB\-\-help\fR
display help text and exit

.TP
\fB\-l\fR, \fB\-\-login\fR
For node mode, login to a specified record. For discovery mode, login to
all discovered targets.
.IP
This option is only valid for discovery and node modes.

.TP
\fB\-m, \-\-mode \fIop\fR
specify the mode. \fIop\fR
must be one of \fIdiscovery\fR, \fInode\fR, or \fIsession\fR.
.IP
If no other options are specified: for \fIdiscovery\fR and \fInode\fR, all
of their respective records are displayed; for \fIsession\fR, all active
sessions and connections are displayed.

.TP
\fB\-M, \-\-map \fIdir\fR
Use the record id associated with the sysfs open-iscsi directory
\fIdir\fR, where \fIdir\fR is the directory of the corresponding
scsi device, for example:

.ft R
	/sys/devices/platform/host0/session0/target0:0:0/0:0:0:0
.IP
Valid only in node mode, and cannot be used with the \fB\-r\fR option.

.TP
\fB\-n\fR, \fB\-\-name=\fIname\fR
Specify a field \fIname\fR in a record. For use with the \fIupdate\fR
operator.
.IP

.TP
\fB\-o\fR, \fB\-\-op=\fIop\fR
Specifies a database operator \fIop\fR. \fIop\fR must be one of
\fInew\fR, \fIdelete\fR, \fIupdate\fR or \fIshow\fR.
.IP
This option is only valid for discovery and node modes.
.IP
\fInew\fR is currently valid only for node mode, it creates a new database
record for a given \fIportal\fR (IP address and port number).
.IP
\fIdelete\fR deletes a specified \fIrecid\fR.
.IP
\fIupdate\fR is currently valid only for node mode, it updates a specified
\fIrecid\fR with \fIname\fR to the specified \fIvalue\fR.
.IP
\fIshow\fR is the default behaviour for node and discovery modes,
\fIname\fR and \fIvalue\fR are currently ignored when used with \fIshow\fR.

.TP
\fB\-p\fR, \fB\-\-portal=\fIip[:port]\fR
Use target portal with ip-address \fIip\fR and \fIport\fR, the default
\fIport\fR value is 3260.
.IP
This option is only valid for discovery, or for node operations with
the \fInew\fR operator.

.TP
\fB\-r\fR, \fB\-\-record=\fI[sid:]recid\fR
Use database record \fIrecid\fR and session id \fIsid\fR. \fIsid\fR
is only required for session mode.

.TP
\fB\-s\fR, \fB\-\-stats\fR
Display session statistics.
.IP
This option is only valid for session mode.

.TP
\fB\-S\fR, \fB\-\-show\fR
When displaying records, do not hide masked values, such as the CHAP
secret (password).
.IP
This option is only valid for node mode.

.TP
\fB\-t\fR, \fB\-\-type=\fItype\fR
\fItype\fR must be \fIsendtargets\fR (or abbreviated as \fIst\fR),
\fIslp\fR, or \fIisns\fR. Currently only sendtargets is supported, see the
DISCOVERY TYPES section.
.IP
This option is only valid for discovery mode.

.TP
\fB\-u\fR, \fB\-\-logout\fR
logout for a specified record.
.IP
This option is only valid for node mode (it is valid but not functional
for session mode).

.TP
\fB\-v\fR, \fB\-\-value=\fIvalue\fR
Specify a \fIvalue\fR for use with the \fIupdate\fR operator.
.IP
This option is only valid for node mode.

.TP
\fB\-V\fR, \fB\-\-version\fR
display version and exit

.SH DISCOVERY TYPES
iSCSI defines 3 discovery types: SendTargets, SLP, and iSNS.

.TP
.B
SendTargets 
A native iSCSI protocol which allows each iSCSI
target to send a list of available targets to the initiator.

.TP
.B
SLP
Optionally an iSCSI target can use the Service Location Protocol (SLP)
to announce the available targets. The initiator can either implement
SLP queries directly or can use a separate tool to acquire the
information about available targets.

.TP
.B
iSNS
iSNS (Internet Storage Name Service) is a proposed standard to record
information about storage volumes within a larger network. In theory
it can be implemented for iSCSI and Fibre Channel. However, no
implementation of the central nameserver mandated by this standard is
currently available.
.P
Currently open-iscsi supports only the
.B
SendTargets
or
.B
st
discovery type. An SLP implementation is under development.

.SH EXAMPLES

.nf
Discover targets at a given IP address:

.ft R
	iscsiadm --mode discovery --type sendtargets --portal 192.168.1.10
.nf

Login, must use a node record id found by the discovery:

.ft R
	iscsiadm --mode node --record 0x12345 --login
.nf

Logout:

.ft R
	iscsiadm --mode node --record 0x12345 --logout
.nf

List node records:

.ft R
	iscsiadm --mode node

.nf

Display all data for a given node record:

.ft R
	iscsiadm --mode node --record 0x12345

.SH FILES
.TP
/etc/iscsid.conf
The configuration file read by \fBiscsid\fR and \fBiscsiadm\fR on startup.
.TP
/etc/initiatorname.iscsi
The file containing the iSCSI initiatorname and initiatoralias read by
\fBiscsid\fR and \fBiscsiadm\fR on startup.
.TP
/var/db/iscsi/discover.db
The discovery database table.
.TP
/var/db/iscsi/node.db
The node database table.

.SH "SEE ALSO"
.BR iscsid (8)

.SH AUTHORS
Open-iSCSI project <http://www.open-iscsi.org/>
.br
Alex Aizman <itn780@yahoo.com>
.br
Dmitry Yusupov <dmitry_yus@yahoo.com>
