.TH "iscsi_fw_login" 8
.SH NAME
iscsi_fw_login \- Login to all iSCSI Firmware targets
.SH SYNOPSIS
.B iscsi_fw_login
.SH DESCRIPTION
This helper function logs into all known iSCSI firmware targets.
.P
It is meant as a helper function to be called by udev when new
firmware targets are detected asynchronously.
.SH AUTHOR
Written by Lee Duncan
.SH "REPORTING BUGS"
Report bugs to <lduncan@suse.com>.
.SH COPYRIGHT
Copyright \(co 2015 Lee Duncan <lduncan@suse.com>
